### ISSUE TITLE
Proposal for WP.org rules - Plugin should serve purpose in 1 (one) specific area

### ISSUE THREAD

**Issue by mtomas7** [WordPress/wporg-plugin-guidelines#65]
I propose an addition to WP.org rules:

– Plugin should serve purpose in 1 (one) specific area.

This way you still can have big plugins as SEO and Security Suits, because they serve that particular area, but you will not have such behemoths as Jetpack. Jetpack would have to decide 1 particular area of service/improvement it offers and other modules would have to be offered as separate plugins, serving their particular area.

This would also discourage other plugin authors to bundle unrelated plugins into one "suite" just to have the option to influence WP Admin search results with multiple keywords.

It would make competition more leveled, as each plugin could propose "suggestion" only for the area that plugin serves.

**Comment by Ipstenu** [comment]
> This would also discourage other plugin authors to bundle unrelated plugins into one "suite" just to have the option to influence WP Admin search results with multiple keywords.
> ...
> It would make competition more leveled, as each plugin could propose "suggestion" only for the area that plugin serves.

Let's not get into Jetpacks flaws and merits for a moment.... I'm unsure what the heart of this suggestion is, that is, what specific problem is it trying to solve?

Having 7 or 14 separate plugins made by Jetpack wouldn't significantly alter the search results in the long term, save in the aspect of 'more downloads and better reviews results in a higher rating.' And if that's what you're trying to address, then in theory we could do this by adjusting the search algorithms.

FWIW, this would be _very_ difficult to manage and enforce. One could argue that Jetpack's services are "Bringing WordPress.com services to self-hosted WordPress installs." That would a very accurate description and would technically fit in with your proposed requirements. 

Given that the majority of Jetpack's services actually do require connectivity to their product, you would create a number of medium sized plugins, all containing the same connectivity suite, which would have to be kept in sync and updated together to ensure compatibility. And they'd probably still rank higher pretty quickly because Jetpack knows how to write good readmes :/

There might be a period of time where Jetpack's Extensions aren't on top, but it wouldn't last long.

**Comment by Ipstenu** [comment]
I'm closing this due to lack of response.

Without a clear explanation as to what specific problem this is meant to solve, we feel it would not be of significant benefit overall. It's possible this needs to be addressed in the  search algorithms, rather than a difficult (if not impossible) to enforce guideline.

I'm not labeling this 'wont-fix' because it's very possible that with a clearer explanation of intent, this may become something we will address, but right now, we just don't have enough information.
